print("Diamond assignment  ")
print("      *********     ")
print("    *************   ")
print("     ***********    ")
print("      *********     ")
print("        *****       ")
print("         ***        ")
print("          *         ")