print("|===============================|")
print("|        EQUITY BANK            |")
print("|     Kasarani Branch           |")
print("|    16th DECEMBER 2077         |")
print("|                               |")
print("|First name: Brandon            |")
print("|Last name :Lee                 |")
print("|Surname   :Lexxy               |")
print("|                               |")
print("|ACC No : 2749790584758457      |")
print("|ACC BAL:$ 9,455,555 dollars    |")
print("|                               |")
print("|          EQUITY               |")
print("|    served by purity           |")
print("|===============================|")